on:
  push:
    branches:
    - main
    tags:
    - 'v*'

name: Release policy

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      # Required to create GH releases
      contents: write
      # Required to push to GHCR
      packages: write
      # Required by cosign keyless signing
      id-token: write

    steps:
      -
        name: Install dependencies
        uses: kubewarden/github-actions/policy-gh-action-dependencies@v3.1.4
      -
        uses: actions/checkout@v3
        with:
          # until https://github.com/actions/checkout/pull/579 is released
          fetch-depth: 0
      -
        name: Install Go tip
        run: |
          curl -sL https://storage.googleapis.com/go-build-snap/go/linux-amd64/$(git ls-remote https://github.com/golang/go.git HEAD | awk '{print $1;}').tar.gz -o gotip.tar.gz
          ls -lah gotip.tar.gz
          mkdir -p ~/sdk/gotip
          tar -C ~/sdk/gotip -xzf gotip.tar.gz
          ~/sdk/gotip/bin/go version
          echo "PATH=$HOME/go/bin:$HOME/sdk/gotip/bin/:$PATH" >> $GITHUB_ENV
      -
        name: Run unit-tests
        run: |
          make test
      -
        name: Build & annotate
        run: |
          GOOS=wasip1 GOARCH=wasm go build -o policy.wasm
          make annotated-policy.wasm
      -
        name: Run e2e tests
        run: |
          make e2e-tests
      -
        name: Release
        uses: kubewarden/github-actions/policy-release@v3.1.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          oci-target: ghcr.io/${{ github.repository_owner }}/tests/go-wasi-template
