on:
  push:
    branches:
      - main
    tags:
      - "v*"

name: Release policy

jobs:
  test:
    name: run tests and linters
    uses: ./.github/workflows/test.yml

  release:
    runs-on: ubuntu-latest
    needs: test

    permissions:
      # Required to create GH releases
      contents: write
      # Required to push to GHCR
      packages: write
      # Required by cosign keyless signing
      id-token: write

    steps:
      - name: Install dependencies
        uses: kubewarden/github-actions/policy-gh-action-dependencies@v3.1.9

      # TODO: remove once we release kubewarden 1.7.0
      - name: remove old kwctl
        run: |
          rm -rf ~/.kwctl
      - name: Install experiemental kwctl
        uses: kubewarden/github-actions/kwctl-installer@v3.1.9
        with:
          KWCTL_VERSION: v1.7.0-rc1
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Run unit-tests
        run: |
          make test
      - name: Build & annotate
        run: |
          GOOS=wasip1 GOARCH=wasm go build -o policy.wasm
          make annotated-policy.wasm
      - name: Run e2e tests
        run: |
          make e2e-tests

      - name: Release
        uses: kubewarden/github-actions/policy-release@v3.1.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          oci-target: ghcr.io/${{ github.repository_owner }}/tests/go-wasi-template
