on: [push, pull_request]
name: Continuous integration
jobs:
  test:
    name: run tests and linters
    uses: kubewarden/github-actions/.github/workflows/reusable-test-policy-go-wasi.yml@f301a7874dd642510fff54a89e4329881bf871ef # v4.6.0
